nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000'] # React frontend URL
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': # Apply CORS to all routes
            allow_origin: ['http://localhost:3000']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
